### ISSUE TITLE
hostname-change - installer fails, but playbook says success

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#108]
This happens intermittently. Seems to be an issue [here](https://git.io/vDsLb). we may have to directly check the exit code instead of using ansible's `success` method

**Comment by sthirugn** [comment]
If this is a easy fix, please check if this can make it to 1.0.1

**Comment by johnpmitsch** [comment]
This should be fixed by this change:
https://github.com/Katello/katello-packaging/pull/420

**Comment by johnpmitsch** [comment]
we don't have the hostname change playbook anymore
