### ISSUE TITLE
Determine if satellite version is 6.3 from backup and add 6.3 support

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#128]
we do this for 6.1 and 6.2 now, but we have to think about how we are going to do so for 6.3

**Comment by johnpmitsch** [comment]
@ehelms maybe you have an idea of how one can tell if a backup comes from 6.3? Right now we check for a satellite-answers file to check for 6.2 vs 6.1

**Comment by sthirugn** [comment]
this issue is a followup from https://github.com/RedHatSatellite/satellite-clone/pull/124/
