### ISSUE TITLE
Fix: Satellite 6.1 installer is not picking correct interface

### ISSUE THREAD

**Issue by jyejare** [RedHatSatellite/satellite-clone#13]
While installing Satellite 6.1, Its not picking the correct interface. The installer is throwing the error : 
```
Could not get the ip address from fact ipaddress_eth0 at /usr/share/katello-installer/modules/foreman_proxy/manifests/proxydhcp.pp:8 on node <hostname_here>
```
The bug is already logged for this issue : https://bugzilla.redhat.com/show_bug.cgi?id=1214627

To fix this issue, there is workaround mention below:
We have to explicitly pass the option --capsule-dhcp-interface <interface_name_on satellite>.

So can we fix this in our tasks/main.yml to use this option while installing 6.1 as:
```
- name: run Satellite 6.1 installer
  command: katello-installer --capsule-dhcp-interface {{ dhcp_interface }}        <------- Here !!
  when: satelliteversion == 6.1
```

**Comment by sthirugn** [comment]
what is your satellite version?  The bug says it is fixed in Satellite 6.1 release.

**Comment by jyejare** [comment]
My satellite version is 6.1.11 when installed with dhcp-interface option.

**Comment by sghai** [comment]
This can be handled w/ ` ip -o link | grep -i 'state UP' | awk -F: '{print $2}'`

**Comment by sghai** [comment]
Will raise a PR to address this

**Comment by sthirugn** [comment]
@sghai are you planning to submit a pr for this?

**Comment by sghai** [comment]
Yeah.. raised PR #63 w/ a change in cmd. Anove cmd won't work in case multiple interfaces are active. I tested that change w/ a good chunk of systems w/ all variations.

**Comment by sthirugn** [comment]
Thank you Sachin.  But I like to have a more generic fix.  Because we won't know if the users (or customers) will use this with one interface or multiple interface.  What if we use your fix as a default option and let users override it with exposing new variables for capsule-dhcp-interface and capsule-dns-interface values in the vars/main.sample.yml file?

**Comment by pgagne** [comment]
I believe ``--capsule-dhcp-interface`` sets the interface in ``/etc/sysconfig/dhcpd``. In my opinion we should give an option whether DHCP should configured or not, and if so with what interface.

**Comment by sghai** [comment]
My PR covers just a workaround not a solution. Ideally this should be handled at product level. But I like the idea what @sthirugn suggested.

**Comment by sthirugn** [comment]
In the irc conversation today, it has been recommended to disable dns, dhcp and tftp in the cloned satellite.  Issue #74 is created to track this change.

@sghai @jyejare I am closing this in favor of Issue #74.  Please ping me or @pgagne if you have questions on this change.
