### ISSUE TITLE
Some issues with docs/helpers for RHEL6 to RHEL7

### ISSUE THREAD

**Issue by pgagne** [RedHatSatellite/satellite-clone#159]
I was trying the RHEL6 to RHEL7 migration and ran into some hiccups:

The order of wording is confusing here:
https://github.com/RedHatSatellite/satellite-clone/blob/master/docs/satellite-clone.md#prerequisites

Since it tells you to run katello-backup, then later tells you about  [satellite-clone/helpers/postgresql_dump.sh]((../helpers/postgresql_dump.sh)). That script seems to also run katello-backup. 

Does the foreman.dump stuff need to be created at the same time as the backup?

Also, the issues might run into some hiccups with that script. When run as root, the postgres user might not have permissions to write to the backup dir.

Do we either want to improve documentation here? or provide better tooling or both?

**Comment by johnpmitsch** [comment]
also seeing permission errors: 
```
-bash: /backup/foreman.dump: Permission denied
-bash: /backup/candlepin.dump: Permission denied
```
