### ISSUE TITLE
Migration through satellite-clone consistently failing while starting postgresql

### ISSUE THREAD

**Issue by sghai** [RedHatSatellite/satellite-clone#160]
Migration through satellite-clone consistently failing at step:

```console
TASK [satellite-clone : Restore postgresql data] *******************************

TASK [satellite-clone : Start postgresql] **************************************
Wednesday 29 March 2017  08:57:27 -0400 (0:00:01.257)       0:28:14.455 ******* 
fatal: [SERVER]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to start service postgresql: Job for postgresql.service failed because the control process exited with error code. See \"systemctl status postgresql.service\" and \"journalctl -xe\" for details.\n"}
```

**Comment by sthirugn** [comment]
did you by chance have both pgsql tar file and foreman/candlepin dump files in the backup folder?

**Comment by sghai** [comment]
Yeah.. both in same folder..

**Comment by sghai** [comment]
@sthirugn so what is expected here ? can't we have  both pgsql tar and dump files in same backup folder ?

**Comment by sthirugn** [comment]
Rerun that scenario from master.  You can see a proper error message now.

Basically we support only one of three scenarios: online, standard, migration.  See the required files for each in https://github.com/RedHatSatellite/satellite-clone/blob/master/docs/satellite-clone.md#prerequisites.

**Comment by sthirugn** [comment]
@sghai I am closing the issue, please reopen if need be.
