### ISSUE TITLE
Rely on katello-restore for restoring content 

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#166]
This is something we should consider to implement starting with 6.3 installs

Here are a few reasons why:
- We duplicate alot of katello-restore logic, which is breaking the DRY principle
- The logic that is used for katello-restore lives upstream, we can help build it out and improve it
- Satellite clone can be an automated way to perform an install and run katello-restore, instead of trying to be a tool with separate logic on its own.

I think everything should stay the way it is for 6.1 and 6.2, and then have some sort of logic that says "if 6.3, use katello-restore", so we can use the newest version of katello-restore

**Comment by evgeni** [comment]
we're using `foreman-maintain` now.
