### ISSUE TITLE
don't ignore errors on install and hostname change anymore

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#177]
we shouldn't skip errors to perform logging as it leads to misleading successful playbook runs when there are actually errors. We have proper logging now and it should handle this.

**Comment by sthirugn** [comment]
this should be duplicate of https://github.com/RedHatSatellite/satellite-clone/issues/176 isnt it?

**Comment by sthirugn** [comment]
Never mind, the other issue is about disassociate capsules ruby script

**Comment by johnpmitsch** [comment]
duplicate of https://github.com/RedHatSatellite/satellite-clone/issues/108
