### ISSUE TITLE
Run migrations after clone

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#183]
After a clone has been run, we should run migrations `foreman-rake db:migrate`. I had a case where the hostname change script failed because of pending migrations when I ran it right after a clone

**Comment by pgagne** [comment]
Can this be fixed by putting the path in quotes?

**Comment by sthirugn** [comment]
May be run the following task for all clones?

```sh
- name: Run installer upgrade (for migration only)
  command: satellite-installer --upgrade
  when: rhel_migration
```
