### ISSUE TITLE
playbook will fail if `activationkey` or `org` set to `changeme` 

### ISSUE THREAD

**Issue by beav** [RedHatSatellite/satellite-clone#196]
If you set `register_to_portal: false` and leave the `activationkey` or `org` set to `changeme`, you will get the following error:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Please update the variables in satellite-clone-vars.yml (after copying satellite-clone-vars.sample.yml)"}
```

The mandatory check stanza should probably account for `register_to_portal` as well.

**Comment by johnpmitsch** [comment]
Note to John: I think this has been fixed, double check

**Comment by rplevka** [comment]
@johnpmitsch, i just hit it, so i think it's still valid

**Comment by johnpmitsch** [comment]
@rplevka thanks for the update!
