### ISSUE TITLE
extracting pulp_data.tar can take up alot of memory

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#208]
Sometimes ansible will throw an error and not complete ( I don't have the error text handy), Memory consumption gets really high when extracting a large (>500GB) tarball.

**Comment by sthirugn** [comment]
In #311 added documentation to do cloning without pulp data in case of large pulp backup files.

**Comment by johnpmitsch** [comment]
There also is a PR upstream to allow splitting up pulp_data.tar, I doubt this will land in 6.2, but it would be helpful if many people ask for it.

https://github.com/theforeman/foreman-packaging/pull/1974

**Comment by johnpmitsch** [comment]
WIth the documentation, I think we can close this issue
