### ISSUE TITLE
Fetch the destination satellite hostname from the backup instead of asking it from the user

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#21]
We should have a preliminary check that the hostname specified is the same as the one in the backups (for the clone playbook).

**Comment by sthirugn** [comment]
Alternatively, I am thinking of deriving the hostname from the config files itself and drop the `hostname` entry in vars/main.yml

`tar zxf config_files.tar.gz etc/foreman-proxy/settings.yml --to-stdout | grep foreman_url |sed 's#.*/##'
`

**Comment by sghai** [comment]
Other way is to fetch the hostname from httpd.conf
`tar -zxf config_files.tar.gz etc/httpd/conf/httpd.conf -O | grep ServerName | awk -F'"' '{print $2}'`

**Comment by sthirugn** [comment]
I decided to remove `hostname` entry in the config and use the logic mentioned in https://github.com/RedHatSatellite/satellite-clone/issues/21#issuecomment-271005183

**Comment by sthirugn** [comment]
Updated title to reflect the proposed solution
