### ISSUE TITLE
Ansible core in now in RHEL7 Extras

### ISSUE THREAD

**Issue by pgagne** [RedHatSatellite/satellite-clone#210]
For RHEL7 Ansible core was added to ``rhel-x86_64-server-extras-7``

So for RHEL7 the user should probably install ansible-core from this. 

See http://docs.ansible.com/ansible/latest/intro_installation.html#latest-release-via-yum

Update the docs and whatever else is needed

**Comment by johnpmitsch** [comment]
note to john: update KCS article
- check if rhel-x86_64-server-extras-7 is disabled

**Comment by pipopopo** [comment]
I suppose this is fixed with https://github.com/RedHatSatellite/satellite-clone/pull/236

**Comment by johnpmitsch** [comment]
it is, thanks!
