### ISSUE TITLE
Update change_hostname script so clients don't have to re-register

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#22]
This involves keeping the ca_cert the same

**Comment by johnpmitsch** [comment]
It may be discussed/developed here https://github.com/Katello/katello-packaging/pull/323

**Comment by sthirugn** [comment]
Need to determine if we need this for Milestone 1.0

**Comment by pgagne** [comment]
This should be an optional operation. In the clone scenario we dont want it to happen.

**Comment by johnpmitsch** [comment]
This will have to land in a later version of sat-clone than 1.0

This actually isn't possible with the way our installer is configured currently. For this to be possible we are going to make the changes to the way the installer handles the certs upstream, let that land in satellite, then update the hostname change script to not have to re-register clients

**Comment by sthirugn** [comment]
Moving this to future Milestone as per the previous comment

**Comment by johnpmitsch** [comment]
This has been changed upstream and we don't use the hostname change playbook anymore
