### ISSUE TITLE
mandatory variables error

### ISSUE THREAD

**Issue by sthirugn** [RedHatSatellite/satellite-clone#222]
I updated activationkey and changeme properly but I got the following error.

TASK [satellite-clone : Check that mandatory variables are updated] **************************************************************************************************
Monday 09 October 2017  20:58:35 -0400 (0:00:00.025)       0:00:03.486 ******** 
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: (({{ activationkey }} == "changeme") or ({{ org }} ==
"changeme")) && register_to_portal

fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check '(({{ activationkey }} == \"changeme\") or ({{ org }} == \"changeme\")) && register_to_portal' failed. The error was: template error while templating string: unexpected char u'&' at 70. String: {% if ((rh-sat-jkl27893489 == \"changeme\") or (5894300 == \"changeme\")) && register_to_portal %} True {% else %} False {% endif %}\n\nThe error appears to have been in '/root/satellite-clone/roles/satellite-clone/tasks/main.yml': line 34, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Check that mandatory variables are updated\n  ^ here\n"}

msg: The conditional check '(({{ activationkey }} == "changeme") or ({{ org }} == "changeme")) && register_to_portal' failed. The error was: template error while templating string: unexpected char u'&' at 70. String: {% if ((rh-sat-jkl27893489 == "changeme") or (5894300 == "changeme")) && register_to_portal %} True {% else %} False {% endif %}

The error appears to have been in '/root/satellite-clone/roles/satellite-clone/tasks/main.yml': line 34, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Check that mandatory variables are updated
  ^ here

I changed the following line to make it work in my box, not sure of the root cause though.
`when: ((activationkey == "changeme") or (org == "changeme")) && register_to_portal`
to 
`when: (activationkey == "changeme") or (org == "changeme")`

**Comment by johnpmitsch** [comment]
should be fixed by https://github.com/RedHatSatellite/satellite-clone/pull/226
