### ISSUE TITLE
restoring postgresql foreman database errored

### ISSUE THREAD

**Issue by sthirugn** [RedHatSatellite/satellite-clone#224]
TASK [satellite-clone : Restore postgresql foreman database] *********************************************************************************************************
Monday 09 October 2017  21:31:36 -0400 (0:00:00.343)       0:31:39.093 ******** 
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: the inline if-expression on line 1 evaluated to false and no else section was defined.\n\nThe error appears to have been in '/root/satellite-clone/roles/satellite-clone/tasks/restore_psql_dump.yml': line 10, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Restore postgresql foreman database\n  ^ here\n"}

msg: the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: the inline if-expression on line 1 evaluated to false and no else section was defined.

The error appears to have been in '/root/satellite-clone/roles/satellite-clone/tasks/restore_psql_dump.yml': line 10, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Restore postgresql foreman database
  ^ here

I removed the newly added disable triggers code to workaround this.

**Comment by johnpmitsch** [comment]
shoudl be fixed by https://github.com/RedHatSatellite/satellite-clone/issues/227
