### ISSUE TITLE
Add option to clean out all pulp repos and resync all pulp-data

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#24]
A user would:
- run a katello-backup w/o pulp content 
- run the clone playbook w/ backup files
- on the cloned machine, the repos would be cleaned out of units and then a "mass re-sync" would be triggered

This would allow  a user to clone w/ content without using pulp_data file (which can be upwards of 1TB) and make for a much faster cloning.

**Comment by johnpmitsch** [comment]
resync all repos script - https://gist.github.com/johnpmitsch/4ae1cfe8ffefb550e668b2256e5f341d

**Comment by johnpmitsch** [comment]
if download policy on the repo is immediate then it won't download content again?

**Comment by johnpmitsch** [comment]
republish the metadata of each repo after deleting the units in mongo pulp-admin or rake task (new one justin wrote - check if in 6.2.z)

**Comment by sthirugn** [comment]
pulling this to Milestone 1.0 as this implements the already existed Milestone 1.0 issue #24

**Comment by johnpmitsch** [comment]
Since half of this issue has been completed, I'm closing for the more specific [issue](https://github.com/RedHatSatellite/satellite-clone/issues/93) about resyncing repos.
