### ISSUE TITLE
migrating Sat6 from RHEL6 causes Sync Plans are run twice

### ISSUE THREAD

**Issue by pmoravec** [RedHatSatellite/satellite-clone#259]
(copy from https://bugzilla.redhat.com/show_bug.cgi?id=1511362 ):

Description of problem:
When one clones a Satellite6 from RHEL6 via satellite-clone, any Sync Plan (either cloned from a parent Satellite or a new one created) is attempted to execute twice on every schedule.

This problem does _not_ happen when cloning Sat6 on RHEL7. Only when cloning from RHEL6 (where katello-backup --online-backup was run)

The root cause is the following:
- satellite-clone installs Satellite incl. filling event_listeners mongo collection
- this collection is not dropped (cf. [1]) while I guess it should be
- once the satellite-clone finishes, event_listeners collection in mongo has 2 records (original from installer and one copied from cloned Sat)
- how Sync Plan is triggered:
  - pulp checks scheduled_calls collection to trigger repo synces
  - once a repo sync finishes, hooks from event_listeners are run to notify katello/foreman
  - so katello gets such trigger and files foreman-task for repo sync (with pulp task ID such that the foreman-task wont trigger new pulp sync task, but just checks it status)
  - pulp executes the triggers for all applicable event_listeners, so having a duplicate ones, a duplicate foreman-task is created (for each and every repo synced)

[1] https://github.com/RedHatSatellite/satellite-clone/blob/master/roles/satellite-clone/tasks/reset_pulp_data.yml#L2

Version-Release number of selected component (if applicable):
satellite-clone-1.1.4-1.el7sat.noarch

How reproducible:
100%

Steps to Reproduce:
1. Clone whatever Satellite (even freshly installed)
2. Have (cloned or created) Sync Plan (idealy with hourly frequency to see it soon)
3. Wait for the Sync Plan execution time and check foreman tasks created
4. check event listeners:
mongo pulp_database --eval "DBQuery.shellBatchSize = 10000000; db.event_listeners.find().shellPrint()"

Actual results:
3. Shows duplicate tasks created / half of them failing with "acquired lock .." error.
4. shows 2 listeners

Expected results:
3. no extra tasks created
4. to show just 1 listener

Additional info:
I was monitoring content of the events_listener table. The table got one new record, then:
- when cloning from RHEL7, this record was removed and replaced by the same record from original Satellite
- when cloning from RHEL6, the record from original Satellite was just _added_ but previous record remained there - thats the problem

(just out of curiosity (if I am right with the way of fix): why we dont drop *all* tables but just some of them?)

**Comment by johnpmitsch** [comment]
Thanks for the detailed report! One thing to consider is just disabling all  sync plans

**Comment by pmoravec** [comment]
Disabling all sync plans wont help. As a valid scenario leading to the bug is:

- clone Satellite (on RHEL6) without a Sync Plan
- `event_listeners` will have 2 records either way
- create a new Sync Plan (and assign it to a Product) on the cloned Satellite
- every repo from the Product will have 2 foreman tasks at the time of Sync Plan execution time

**Comment by johnpmitsch** [comment]
thanks for the update, I'll look into it!

**Comment by johnpmitsch** [comment]
@pmoravec was this a backup w/o pulp_data?

**Comment by pmoravec** [comment]
I run `katello-backup` without `--skip-pulp-data` but I *think* this option should not matter if it deals with `/var/lib/pulp` and not with `mongo` data.
