### ISSUE TITLE
satellite-clone says config_files.tar.gz is not present

### ISSUE THREAD

**Issue by vision2910** [RedHatSatellite/satellite-clone#271]
On a plain RHEL7.4 system, katello-backup(generated on the existing Satellite 6.2.12) is downloaded. 
Required changes are done in the satellite-clone-vars.yml file. Every time when the-

`#satellite-clone` 

is ran, it is throwing error-
TASK [satellite-clone : Fail if the config tar file is not present or not accessible] ******************************************
Tuesday 21 November 2017  21:10:34 +0530 (0:00:00.203)       0:00:02.281 ****** 
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "/backup/config_files.tar.gz is not present or not accessible"}

msg: /backup/config_files.tar.gz is not present or not accessible

> 

satellite-clone version: satellite-clone-1.1.4-1.el7sat.noarch

**Comment by sthirugn** [comment]
can you paste `ls -l /backup`?

**Comment by vision2910** [comment]
# pwd
/root/satellite-clone

# ls -l /backup/
total 40385024
-rw-r--r--. 1 root root     1093452 Nov 21 21:51 config_files.tar.gz
drwxrwx---. 2 root root         193 Nov 20 19:21 katello-backup
-rw-r--r--. 1 root root           0 Nov 21 21:51 metadata
-rw-r--r--. 1 root root 11841597440 Nov 21 21:52 mongo_data.tar
-rw-r--r--. 1 root root   663828480 Nov 21 21:52 pgsql_data.tar
-rw-r--r--. 1 root root 28847742976 Nov 21 21:54 pulp_data.tar

**Comment by johnpmitsch** [comment]
try moving/removing the `katello-backup` folder. If that doesn't work, what are the permissions of /backup? `ls -al`

**Comment by evgeni** [comment]
going to close this as user error

please re-open if you can still reproduce on a recent version of satellite and satellite-clone
