### ISSUE TITLE
 [HTB] Destination is not configurable

### ISSUE THREAD

**Issue by lzap** [RedHatSatellite/satellite-clone#276]
Root partition is usually small on production systems and everything else is on separate volumes. Clone tool only clones to root, there is no way to override this and the check. We need this to be configurable.

**Comment by Rocco83** [comment]
I would suggest to leverage on the space needed based on real data and not on "forecast".
75GB may be a lot or not, it depend on the source.
The tool should be able to check for every directory the needed space and perform the calculation over the proper filesystems.

As extracting data from a tar may be not easy, a possible workaround is to make some one liner to be run on the source server, that will write the config for the various items to be checked.

**Comment by lzap** [comment]
I am closing the ticket, the source backup directory is actually configurable and target backup directory as well (via `katello-backup` tool option). I think I misunderstood.
