### ISSUE TITLE
[HTB] Restored files have wrong SELinux contexts

### ISSUE THREAD

**Issue by lzap** [RedHatSatellite/satellite-clone#277]
When backups are restored and pulp/candlepin/katello selinux policies are not yet loaded (rpm packages are not even installed), then contexts cannot be restored. There are warnings during extracting tarballs:

    tar: setfileconat: Cannot set SELinux context for file 'var/lib/candlepin/hornetq/bindings/hornetq-bindings-1.bindings': Invalid argument

Various components will then fail to start (e.g. Candlepin - unable to read CRT files) in enforcing.

SOLUTION A: Install pulp-selinux, candlepin-selinux, foreman*-selinux and katello-selinux BEFORE any files gets extracted.

SOLUTION B: Add additional step - relabel all files which has been restored from backup AFTER all policies are loaded. This can be very time-consuming operation when doing this with pulp content, but we must do that when in enforcing. Therefore do:

    restorecon /etc /all/paths/coming/from/tarballs

**Comment by sideangleside** [comment]
+1 to Solution A. Since you are going to have to take the expense of the `stat()` call anyway, it is better to only do it once.

**Comment by lzap** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1518723

**Comment by johnpmitsch** [comment]
Turns out this wasn't a bug (see bugzilla for more info). Please reopen if I am misunderstanding.
