### ISSUE TITLE
Better handle selinux labels during mongo db restoration

### ISSUE THREAD

**Issue by JacobCallahan** [RedHatSatellite/satellite-clone#289]
In a recent clone attempt, my mongo database restoration failed. Another person was able to determine that the issue was with selinux labels. He was able to mitigate this by
```
restorecon -Rv /var/lib/mongodb
```
In the future, this should be handled by the clone tool.

**Comment by beav** [comment]
I think some good candidates for relabel are:

`/var/lib/mongodb`
`/var/lib/pulp`
`/var/lib/pgsql`

**Comment by johnpmitsch** [comment]
we did add the ability to restorecon the filesystem [here](https://github.com/RedHatSatellite/satellite-clone/pull/249) but maybe there are some file paths we should do by default. The concern is that restorecon could potentially take a long time (especially with /var/lib/pulp) if the user is dealing with network storage or a slow disk, which made us make the setting "opt-in".

**Comment by evgeni** [comment]
We've seen this a few times where MongoDB (and its SELinux policy) is installed in the same transaction as an *update* to the base SELinux policy of the OS. The docs say that you should utilize a fully uptodate system and recent Satellite versions dropped MongoDB support anyways → closing.
