### ISSUE TITLE
Check for and remove jmx.conf

### ISSUE THREAD

**Issue by JacobCallahan** [RedHatSatellite/satellite-clone#290]
If a backup contains a jmx.conf file, it can fail a satellite installation. Removing the file allows tomcat to run correctly and the installation to proceed.
File location should be here:
/etc/tomcat/conf.d/jmx.conf

**Comment by johnpmitsch** [comment]
To make sure I understand correctly the backup has a config_files.tar.gz file that contains /etc/tomcat/conf.d/jmx.conf?

**Comment by JacobCallahan** [comment]
That is correct. Alternatively, it **might** be possible to rename the file before the installer and back afterward to keep it intact, but I can't confirm that.
