### ISSUE TITLE
trouble with cache / add --cleancache option?

### ISSUE THREAD

**Issue by pondrejk** [RedHatSatellite/satellite-clone#292]
Suppose this scenario: my playbook run fails on `[satellite-clone : Check if root has enough space] `, which is accurate. I rearrange my partitions and run again, getting the same error. This is because  set_fact for root size is cached [1], so the next run doesn't check the actual root size. Not sure if cacheable can be dropped here, but if not, we should at least inform user about the necessity to clean the cache and where to find it (I suppose /usr/share/satellite-clone/cache/localhost). Even nicer would be to have a `satellite-clone --clean-cache` option

[1] https://github.com/RedHatSatellite/satellite-clone/blob/master/roles/satellite-clone/tasks/pre_install_check.yml#L28

**Comment by johnpmitsch** [comment]
closing as this has been fixed, thanks @pondrejk!
