### ISSUE TITLE
satellite-clone fails silently when there is any non-zero return code in the restore processes

### ISSUE THREAD

**Issue by sthirugn** [RedHatSatellite/satellite-clone#299]
Workaround is to comment out the relevent postgres command to proceed:
task1: runuser - postgres -c ""dropdb foreman""
task2: runuser - postgres -c ""pg_restore {{ ' --disable-triggers' if disable_postgres_triggers else ''}} -C -d postgres {{ backup_dir }}/foreman.dump"""

This is a problem because there is no indication to the user that the error actually occurred.

**Comment by johnpmitsch** [comment]
What was the error? This may have been from having disable-triggers on

**Comment by sthirugn** [comment]
I don't have the error now, this happened with a customer. If disable-triggers was on by default during beta, they used the default settings.

**Comment by johnpmitsch** [comment]
I'm not sure I understand, there was no indication that the error occurred, but they had to comment out the task to continue? What was the error message? This needs more details, I am not sure how to fix this w/o more details or the backup used.

**Comment by evgeni** [comment]
we don't call dropdb and pg_restore anymore, but rely on foreman-maintain for that, closing
