### ISSUE TITLE
Have a better error msg when Satellite repo is not enabled

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#305]
When running sat-clone w/ manual registration of repos, we can do a better job checking for Satellite repo and instructing users to manually setup the repos if they are not enabled. Currently yum errors out if repos are not enabled.

**Comment by sthirugn** [comment]
Better separate the portal registration and repo enable steps so enabling repos happen always

**Comment by johnpmitsch** [comment]
what should happen is:
1) customer attaches satellite subs
2) customer runs sat-clone
3) we disable all repos and enable the correct ones (like the docs specify)
4) happy clone continues :smiley:
