### ISSUE TITLE
Wrapper Script?

### ISSUE THREAD

**Issue by pgagne** [RedHatSatellite/satellite-clone#32]
Do we want to add some sort of wrapper around the playbook to shorten the steps and make it so the user does have to edit ansible config and inventory files as much. 

Here is what I was thinking 

```
satellite-clone-tool --source=<clone_from_host> --dest=<clone_to_host> --rhel-version=7 --satellite-version=6.2 --activation-key=<ak> ...
```

**Comment by mccun934** [comment]
+1, this is far more usable

**Comment by johnpmitsch** [comment]
We can use a local vars file and keep the main.yml file within the role as a default

**Comment by johnpmitsch** [comment]
We switched to a local vars file and that is as easy of a process as we could make it, if there are any other ideas please reopen
