### ISSUE TITLE
Prevent cloning a backup to the wrong satellite version

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#324]
We should prevent users from cloning a backup to the wrong Satellite version. i.e. 6.2 repos are enabled, but the user is using a 6.3 backup

**Comment by sideangleside** [comment]
👍 This issue bit me hard (and with a rather cryptic error)

**Comment by sthirugn** [comment]
Perhaps we can use the metadata created by katello-backup to find if the backup is 6.2 or 6.3.  We can keep the old logic to identify the 6.1 backup.
```sh
cat /backup/satellite-backup-20180216115757/metadata.yml | grep '^- satellite-6.3'
cat /backup/satellite-backup-20180216115757/metadata.yml | grep '^- satellite-6.2'
```
