### ISSUE TITLE
satellite-clone fails on a satellite 6.3 installed with puppet 4

### ISSUE THREAD

**Issue by sthirugn** [RedHatSatellite/satellite-clone#328]
I had to add a task to workaround:
```sh
- name: enable puppet4 rpms
  command: subscription-manager repos --enable rhel-7-server-satellite-6.3-puppet4-rpms
  when: enable_repos
```

But the permanent fix will be to check the `puppet-agent` package availability in backup metadata.yml:
```sh
cat /backup/satellite-backup-20180313213434/metadata.yml | grep 'puppet-agent'
```
If the above returned an item (or two - I see `puppet-agent-1` and `puppet-agent-oauth`), then it is puppet4. In other words, a return value of 0 for the above command will indicate puppet4.

**Comment by sthirugn** [comment]
Add Evgeni and Eric as reviewers after implementing this.

**Comment by johnpmitsch** [comment]
we should actually add this to the check_metadata_for_satellite_version module since that is already parsing the yml. This will allow us to return something like
```python
{ satellite_version: 6.3, puppet_version: 4 }
```

**Comment by sthirugn** [comment]
even better, yeah + to use the new ansible module
