### ISSUE TITLE
libselinux-python package install step should be after when instance is subscribed to rhel repos

### ISSUE THREAD

**Issue by sghai** [RedHatSatellite/satellite-clone#35]
package install [step](https://github.com/RedHatSatellite/satellite-clone/blob/master/roles/sat6repro/tasks/main.yml#L30) should be after [this](https://github.com/RedHatSatellite/satellite-clone/blob/master/roles/sat6repro/tasks/main.yml#L30)
 otherwise, install may failed with error:

```console
 FAILED! => {"changed": false, "failed": true, "msg": "There are no enabled repos.\n Run \"yum repolist all\" to see the repos you have.\n You can enable repos with yum-config-manager --enable <repo>\n", "rc": 1, "results": []}
```

**Comment by sthirugn** [comment]
PR #36 is merged now.
