### ISSUE TITLE
(Re)populating pulp content

### ISSUE THREAD

**Issue by sthirugn** [RedHatSatellite/satellite-clone#5]
For fast cloning, this project does not take pulp content into cosideration while cloning.  There are potentially two ways to fix this:

1. Give an option to the user to supply pulp content.
2. Find and provide a way to the user to force sync all the repos.

**Comment by johnpmitsch** [comment]
I think we just need to do #1, as a user will have the pulp_content file from a backup available

**Comment by sthirugn** [comment]
Option 2 will be helpful, if you got a satellite backup from someone without pulp content, but you need to install a full fledged Satellite from the available backup.  I think this is a common case for support team now as pulp content is huge and is not often being sent for troubleshooting purposes.

**Comment by johnpmitsch** [comment]
Thats a fair point, how about we start with option 1 and then add option 2?

**Comment by sthirugn** [comment]
See https://pulp.plan.io/issues/2248 to resync a repo

**Comment by sthirugn** [comment]
@johnpmitsch can this issue be closed now?

**Comment by johnpmitsch** [comment]
We still have to add 2) Find and provide a way to the user to force sync all the repos

I have  a [script for mass resync](https://gist.github.com/johnpmitsch/4ae1cfe8ffefb550e668b2256e5f341d) which we can wrap in an ansible playbook. I can do that

**Comment by sthirugn** [comment]
Option 1 of the original description is completed.
Option 2 of the original description will be done when https://github.com/RedHatSatellite/satellite-clone/pull/65 is merged.

**Comment by sthirugn** [comment]
Option 2 will be covered as part of https://github.com/RedHatSatellite/satellite-clone/issues/24
