### ISSUE TITLE
libselinux-python required for RHEL6

### ISSUE THREAD

**Issue by pgagne** [RedHatSatellite/satellite-clone#53]
Ran the clone-tool with the destination as the control host. Running RHEL6.

Looks like we need libselinux-python on the destination host maybe?
```
TASK [sat6repro : create /etc/hosts] *******************************************
fatal: [10.8.0.146]: FAILED! => {"changed": true, "failed": true, "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}
	to retry, use: --limit @/root/suresh-sat-clone/satellite-clone-playbook.retry
```

**Comment by johnpmitsch** [comment]
mabye we have to install libselinux-python when using rhel6

**Comment by johnpmitsch** [comment]
also we could check if ansible_connection is local if this only happens when using one host
