### ISSUE TITLE
Add arg to control node setup script to for backup files

### ISSUE THREAD

**Issue by pgagne** [RedHatSatellite/satellite-clone#59]
i was thinking, perhaps this script could take the path to the backup as an argument and make symlinks to the files in roles/sat6repro/files

This should do the trick:

```
$BACKUPS_PATH=$1
...
ln -s --force $BACKUPS_PATH/* roles/sat6repro/files/
```

**Comment by johnpmitsch** [comment]
@pgagne @sthirugn seeing as we take that arg [here](https://github.com/RedHatSatellite/satellite-clone/blob/master/roles/sat6repro/vars/main.sample.yml#L29) can we close this?

**Comment by sthirugn** [comment]
looks like this is written when we created backup files in roles/sat6repro/files - this is changed and not valid anymore. I will let @pgagne review and close this.

**Comment by pgagne** [comment]
Closing this since it does not apply anymore
