### ISSUE TITLE
installing libselinux-python happens before subscribing to a repo

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#66]
To reproduce, run sat-clone using two hosts. On the destination node, make sure it is a clean install with no repos enabled.

TASK [sat6repro : install libselinux-python for rhel6] *************************
fatal: [192.168.121.230]: FAILED! => {"changed": false, "failed": true, "msg": "There are no enabled repos.\n Run \"yum repolist all\" to see the repos you have.\n You can enable repos with yum-config-manager --enable <repo>\n", "rc": 1, "results": []}
	to retry, use: --limit @/root/satellite-clone/satellite-clone-playbook.retry

**Comment by sthirugn** [comment]
Addressed in PR #68
