### ISSUE TITLE
Registration to the Customer Portal should be optional

### ISSUE THREAD

**Issue by sideangleside** [RedHatSatellite/satellite-clone#73]
As a user, I'd like for it to not be mandatory to register to the Customer Portal as a prerequisite of using satellite-clone. 

I may be using satellite-clone to test an upgrade or reproduce a problem, and I may want to do this offline or I may only have a single satellite subscription that I dont wish to remove from my production system. 

In this use case, I would expect that the user would be required to provide working yum repos (for RHEL, RHSCL & Satellite) prior to invoking the playbook.

**Comment by sthirugn** [comment]
This is a valid use case and perhaps should be supported in Milestone 1.0
