### ISSUE TITLE
Add mass resync of repos playbook

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#93]
Adding a playbook to resync "everything" would be helpful after users sync w/o pulp data and are left with blank repos

**Comment by sideangleside** [comment]
I think in executing this, i'd want to change the download_policy of the repos. That way the mass-resync can happen asynchronously.

**Comment by sthirugn** [comment]
Also need to consider publish/promote of existing content views

**Comment by johnpmitsch** [comment]
sat-clone requires pulp-data.tar, so a mass re-sync isn't needed
