### ISSUE TITLE
Cant sync content to capsule that was moved from one satellite to another. 

### ISSUE THREAD

**Issue by pgagne** [RedHatSatellite/satellite-clone#95]
Steps:

1. Started with Sat1. Attached capsule1. 
2. Cloned Sat1 to Sat2. 
3. On Sat2 generate the capsule certs for capsule1
4. Unregistered capsule1 from Sat1. 
5. register capsule1 to sat2
6. Rerun the the capsule installer with new certs. 
7. Run capsule content sync on Sat2 for capsule1

Task fails with the following warning:
```
Host did not respond within 20 seconds. Sync has been cancelled. Is katello-agent installed and goferd running on the Host?
``` 

For reference that was running 6.1 on RHEL7

**Comment by johnpmitsch** [comment]
@pgagne did you find some more info on this? I think there was something about the hosts file?

**Comment by sthirugn** [comment]
this is a user error - the capsule was not able to talk to the new cloned satellite since the dns was still pointing to the old satellite. I suggested him to add a host entry in /etc/hosts in capsule to override dns and it fixed the issue.  I will let @pgagne review and close this.

**Comment by johnpmitsch** [comment]
closing since this seems to have been a user issue, @pgagne re-open if you think this is an issue with sat-clone
